name: hello world
on:
   push:
   branches : ["main" ]

jobs:
  build:
    runs-on:self-hosted

    steps:
    - name: checkoutcode
      uses: actions/checkout@v3   
    - name: run scripit
      run: hello world 
